// <auto-generated />
using Bolighoesteren;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bolighoesteren.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190227111646_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilterLibrary.Ejendom", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("HashCode");

                    b.Property<string>("Link");

                    b.Property<string>("Photo");

                    b.Property<string>("Postcode");

                    b.Property<string>("Price");

                    b.HasKey("PropertyId");

                    b.HasIndex("Postcode");

                    b.ToTable("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
