// <auto-generated />
using Bolighoesteren;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bolighoesteren.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190227173853_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilterLibrary.Ejendom", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse");

                    b.Property<int>("Areal");

                    b.Property<string>("BoligydForbrugsafh");

                    b.Property<int>("Byggeår");

                    b.Property<string>("Ejerudgifter");

                    b.Property<string>("Foto");

                    b.Property<int>("GrundAreal");

                    b.Property<int>("HashCode");

                    b.Property<string>("KvadratmeterPris");

                    b.Property<string>("Liggetid");

                    b.Property<string>("Link");

                    b.Property<int>("Postnummer");

                    b.Property<string>("Pris");

                    b.Property<string>("Prisudvikling");

                    b.Property<int>("Rum");

                    b.HasKey("PropertyId");

                    b.HasIndex("Postnummer");

                    b.ToTable("Ejendomme");
                });
#pragma warning restore 612, 618
        }
    }
}
